version: "3.8"
services:

  db_mongo:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongo-data:/data/db
    networks:
      - asana    

  backend:
    container_name: backend
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db_mongo
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=db_mongo
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - IS_CONTAINER=$STATUS
    networks:
      - asana  
    volumes:
      - './backend/uploads:/backend/src/uploads:rw'
      - './backend/logs:/backend/src/logs:rw'
    stdin_open: true
    tty: true

networks:
  asana:
    driver: bridge

volumes:
  mongo-data:
    driver: local
